create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique references auth.users(id) on delete cascade,
  name text not null,
  email text not null unique,
  role text not null check (role in ('student', 'faculty', 'admin')),
  roll_no text unique,
  department text,
  year text,
  section text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  name text not null,
  faculty_id bigint not null references public.profiles(id) on delete restrict,
  department text not null,
  year text not null,
  section text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.notices (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  category text not null check (category in ('general', 'exam', 'assignment', 'event', 'placement', 'holiday')),
  priority text not null check (priority in ('normal', 'important', 'urgent')),
  department text,
  year text,
  section text,
  due_date date,
  needs_ack boolean not null default false,
  status text not null check (status in ('draft', 'published')),
  publish_at timestamptz not null default now(),
  created_by bigint not null references public.profiles(id) on delete restrict,
  pinned boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.read_receipts (
  notice_id bigint not null references public.notices(id) on delete cascade,
  user_id bigint not null references public.profiles(id) on delete cascade,
  read_at timestamptz not null default now(),
  ack_at timestamptz,
  primary key (notice_id, user_id)
);

create table if not exists public.materials (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.courses(id) on delete cascade,
  unit text not null,
  title text not null,
  description text,
  type text not null check (type in ('file', 'link')),
  file_name text,
  link text,
  storage_path text unique,
  visibility text not null check (visibility in ('draft', 'published')),
  uploaded_by bigint not null references public.profiles(id) on delete restrict,
  uploaded_at timestamptz not null default now(),
  version integer not null default 1 check (version > 0),
  check ((type = 'file' and file_name is not null and storage_path is not null) or (type = 'link' and link is not null))
);

create table if not exists public.material_views (
  id bigint generated by default as identity primary key,
  material_id bigint not null references public.materials(id) on delete cascade,
  user_id bigint not null references public.profiles(id) on delete cascade,
  viewed_at timestamptz not null default now()
);

create table if not exists public.bookmarks (
  user_id bigint not null references public.profiles(id) on delete cascade,
  item_type text not null check (item_type in ('notice', 'material')),
  item_id bigint not null,
  created_at timestamptz not null default now(),
  primary key (user_id, item_type, item_id)
);

create index if not exists notices_created_by_idx on public.notices(created_by);
create index if not exists notices_audience_idx on public.notices(department, year, section, status, publish_at);
create index if not exists materials_course_visibility_idx on public.materials(course_id, visibility);
create index if not exists material_views_material_idx on public.material_views(material_id);
create index if not exists bookmarks_item_idx on public.bookmarks(item_type, item_id);

create or replace function public.current_profile_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select id from public.profiles where auth_user_id = auth.uid() and active limit 1
$$;

create or replace function public.current_profile_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where auth_user_id = auth.uid() and active limit 1
$$;

create or replace function public.is_profile_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_profile_role() = 'admin', false)
$$;

create or replace function public.matches_current_audience(target_department text, target_year text, target_section text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles p
    where p.auth_user_id = auth.uid() and p.active and p.role = 'student'
      and (target_department is null or target_department = '' or target_department = p.department)
      and (target_year is null or target_year = '' or target_year = p.year)
      and (target_section is null or target_section = '' or target_section = p.section)
  )
$$;

create or replace function public.get_student_email(p_roll_no text)
returns text
language sql
stable
security definer
set search_path = public
as $$
  select email from public.profiles
  where role = 'student' and active and lower(roll_no) = lower(trim(p_roll_no))
  limit 1
$$;

create or replace function public.can_access_material_file(object_name text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.materials m
    join public.courses c on c.id = m.course_id
    where m.storage_path = object_name
      and (
        public.is_profile_admin()
        or m.uploaded_by = public.current_profile_id()
        or (
          m.visibility = 'published'
          and exists (
            select 1 from public.profiles p
            where p.auth_user_id = auth.uid() and p.active and p.role = 'student'
              and p.department = c.department and p.year = c.year and p.section = c.section
          )
        )
      )
  )
$$;

create or replace view public.profile_directory with (security_invoker = false) as
  select id, name, role
  from public.profiles;
grant select on public.profile_directory to authenticated;

create or replace view public.staff_directory with (security_invoker = false) as
  select id, name, role, department, year, section, active
  from public.profiles
  where public.current_profile_role() in ('faculty', 'admin');
grant select on public.staff_directory to authenticated;

alter table public.profiles enable row level security;
alter table public.courses enable row level security;
alter table public.notices enable row level security;
alter table public.read_receipts enable row level security;
alter table public.materials enable row level security;
alter table public.material_views enable row level security;
alter table public.bookmarks enable row level security;

create policy "profiles visible to self and admins" on public.profiles
  for select to authenticated
  using (auth_user_id = auth.uid() or public.is_profile_admin());
create policy "admins update profiles" on public.profiles
  for update to authenticated using (public.is_profile_admin()) with check (public.is_profile_admin());

create policy "courses visible to authenticated users" on public.courses
  for select to authenticated using (true);
create policy "admins manage courses" on public.courses
  for all to authenticated using (public.is_profile_admin()) with check (public.is_profile_admin());

create policy "notices visible by role and audience" on public.notices
  for select to authenticated using (
    public.is_profile_admin()
    or created_by = public.current_profile_id()
    or (
      status = 'published' and publish_at <= now()
      and public.matches_current_audience(department, year, section)
    )
  );
create policy "staff create notices" on public.notices
  for insert to authenticated with check (
    created_by = public.current_profile_id()
    and public.current_profile_role() in ('faculty', 'admin')
  );
create policy "owners and admins update notices" on public.notices
  for update to authenticated
  using (created_by = public.current_profile_id() or public.is_profile_admin())
  with check (created_by = public.current_profile_id() or public.is_profile_admin());
create policy "owners and admins delete notices" on public.notices
  for delete to authenticated using (created_by = public.current_profile_id() or public.is_profile_admin());

create policy "read receipts visible to reader and notice staff" on public.read_receipts
  for select to authenticated using (
    user_id = public.current_profile_id()
    or public.is_profile_admin()
    or exists (select 1 from public.notices n where n.id = notice_id and n.created_by = public.current_profile_id())
  );
create policy "students create own read receipts" on public.read_receipts
  for insert to authenticated with check (
    user_id = public.current_profile_id() and public.current_profile_role() = 'student'
  );
create policy "students update own read receipts" on public.read_receipts
  for update to authenticated
  using (user_id = public.current_profile_id() and public.current_profile_role() = 'student')
  with check (user_id = public.current_profile_id() and public.current_profile_role() = 'student');

create policy "materials visible to owner staff and enrolled class" on public.materials
  for select to authenticated using (
    public.is_profile_admin()
    or uploaded_by = public.current_profile_id()
    or exists (
      select 1 from public.courses c
      join public.profiles p on p.auth_user_id = auth.uid() and p.active and p.role = 'student'
      where c.id = course_id and c.department = p.department and c.year = p.year and c.section = p.section
        and visibility = 'published'
    )
  );
create policy "staff upload materials" on public.materials
  for insert to authenticated with check (
    uploaded_by = public.current_profile_id() and public.current_profile_role() in ('faculty', 'admin')
  );
create policy "owners and admins update materials" on public.materials
  for update to authenticated
  using (uploaded_by = public.current_profile_id() or public.is_profile_admin())
  with check (uploaded_by = public.current_profile_id() or public.is_profile_admin());
create policy "owners and admins delete materials" on public.materials
  for delete to authenticated using (uploaded_by = public.current_profile_id() or public.is_profile_admin());

create policy "material views visible to reader and owner staff" on public.material_views
  for select to authenticated using (
    user_id = public.current_profile_id()
    or public.is_profile_admin()
    or exists (select 1 from public.materials m where m.id = material_id and m.uploaded_by = public.current_profile_id())
  );
create policy "students record own material views" on public.material_views
  for insert to authenticated with check (
    user_id = public.current_profile_id() and public.current_profile_role() = 'student'
  );

create policy "users manage their own bookmarks" on public.bookmarks
  for all to authenticated
  using (user_id = public.current_profile_id())
  with check (user_id = public.current_profile_id());

create or replace function public.remove_deleted_notice_bookmarks()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  delete from public.bookmarks where item_type = 'notice' and item_id = old.id;
  return old;
end;
$$;
create or replace function public.remove_deleted_material_bookmarks()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  delete from public.bookmarks where item_type = 'material' and item_id = old.id;
  return old;
end;
$$;
drop trigger if exists notices_remove_bookmarks on public.notices;
create trigger notices_remove_bookmarks after delete on public.notices
  for each row execute function public.remove_deleted_notice_bookmarks();
drop trigger if exists materials_remove_bookmarks on public.materials;
create trigger materials_remove_bookmarks after delete on public.materials
  for each row execute function public.remove_deleted_material_bookmarks();

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('materials', 'materials', false, 52428800, array[
  'application/pdf', 'application/msword',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.ms-powerpoint',
  'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  'application/zip', 'image/png', 'image/jpeg'
])
on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "staff upload their own material files" on storage.objects
  for insert to authenticated with check (
    bucket_id = 'materials'
    and (storage.foldername(name))[1] = public.current_profile_id()::text
    and public.current_profile_role() in ('faculty', 'admin')
  );
create policy "authorized users read material files" on storage.objects
  for select to authenticated using (bucket_id = 'materials' and public.can_access_material_file(name));
create policy "owners and admins delete material files" on storage.objects
  for delete to authenticated using (
    bucket_id = 'materials'
    and ((storage.foldername(name))[1] = public.current_profile_id()::text or public.is_profile_admin())
  );

grant execute on function public.current_profile_id() to authenticated;
grant execute on function public.current_profile_role() to authenticated;
grant execute on function public.is_profile_admin() to authenticated;
grant execute on function public.matches_current_audience(text, text, text) to authenticated;
grant execute on function public.can_access_material_file(text) to authenticated;
grant execute on function public.get_student_email(text) to anon, authenticated;
