drop view if exists public.profile_directory;
drop view if exists public.staff_directory;

update public.users set role = lower(role) where lower(role) in ('student', 'faculty', 'admin');
update public.users set active = true where active is null;
alter table public.users alter column active set default true;
alter table public.users alter column active set not null;
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.users'::regclass and conname = 'users_role_valid'
  ) then
    alter table public.users add constraint users_role_valid check (role in ('student', 'faculty', 'admin'));
  end if;
end $$;

create table public.students (
  user_id bigint primary key references public.users(id) on delete cascade,
  roll_no text not null unique,
  program_code text not null,
  department text,
  year text not null,
  section text not null,
  constraint student_program_code_format check (program_code ~ '^[a-zA-Z]{2,8}$')
);

create table public.faculty (
  user_id bigint primary key references public.users(id) on delete cascade,
  department text,
  is_hod boolean not null default false
);

create table public.administrators (
  user_id bigint primary key references public.users(id) on delete cascade
);

insert into public.students (user_id, roll_no, program_code, department, year, section)
select u.id,
  coalesce(nullif(u.roll_no, ''), 'legacy-' || u.id::text),
  case when lower(coalesce(u.department, '')) ~ '^[a-z]{2,8}$' then lower(u.department)
    when lower(left(split_part(u.email, '@', 1), 3)) ~ '^[a-z]{2,8}$' then lower(left(split_part(u.email, '@', 1), 3))
    else 'mca' end,
  coalesce(u.department, ''), coalesce(u.year, ''), coalesce(u.section, '')
from public.users u
where u.role = 'student'
on conflict (user_id) do nothing;
insert into public.faculty (user_id, department)
select id, department from public.users where role = 'faculty'
on conflict (user_id) do nothing;
insert into public.administrators (user_id)
select id from public.users where role = 'admin'
on conflict (user_id) do nothing;

alter table public.student rename to legacy_student_records;

alter table public.courses add column if not exists program_code text;
update public.courses set program_code = lower(coalesce(nullif(department, ''), 'mca')) where program_code is null;
alter table public.courses alter column program_code set not null;
alter table public.courses add column if not exists course_code text;
update public.courses set course_code = upper(left(regexp_replace(name, '[^A-Za-z]', '', 'g'), 8)) where course_code is null;
alter table public.courses alter column course_code set not null;
alter table public.courses alter column section drop not null;

alter table public.notices add column if not exists course_id bigint references public.courses(id) on delete set null;
alter table public.notices add column if not exists image_path text;
alter table public.materials add column if not exists program_code text;
update public.materials m set program_code = c.program_code from public.courses c where c.id = m.course_id and m.program_code is null;
alter table public.materials alter column program_code set not null;

do $$
declare
  relation_constraint record;
  rewritten_definition text;
begin
  for relation_constraint in
    select conrelid::regclass as relation_name, conname, pg_get_constraintdef(oid) as definition
    from pg_constraint
    where contype = 'f' and confrelid = 'public.profiles'::regclass
  loop
    execute format('alter table %s drop constraint %I', relation_constraint.relation_name, relation_constraint.conname);
    rewritten_definition := regexp_replace(relation_constraint.definition, 'REFERENCES (public\.)?profiles', 'REFERENCES public.users');
    execute format('alter table %s add constraint %I %s',
      relation_constraint.relation_name, relation_constraint.conname, rewritten_definition);
  end loop;
end $$;

do $$
declare
  dependent_policy record;
begin
  for dependent_policy in
    select p.polname, table_namespace.nspname as schema_name, table_relation.relname as table_name
    from pg_policy p
    join pg_class table_relation on table_relation.oid = p.polrelid
    join pg_namespace table_namespace on table_namespace.oid = table_relation.relnamespace
    join pg_depend dependency
      on dependency.classid = 'pg_policy'::regclass and dependency.objid = p.oid
    where dependency.refclassid = 'pg_class'::regclass
      and dependency.refobjid = 'public.profiles'::regclass
  loop
    execute format('drop policy if exists %I on %I.%I',
      dependent_policy.polname, dependent_policy.schema_name, dependent_policy.table_name);
  end loop;
end $$;

drop table public.profiles;

create table public.calendar_events (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  title text not null,
  description text,
  event_date date not null,
  created_at timestamptz not null default now()
);

create table public.notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  event_type text not null check (event_type in ('notice', 'material')),
  title text not null,
  body text not null,
  notice_id bigint references public.notices(id) on delete cascade,
  material_id bigint references public.materials(id) on delete cascade,
  created_at timestamptz not null default now(),
  read_at timestamptz,
  check ((event_type = 'notice' and notice_id is not null and material_id is null)
      or (event_type = 'material' and material_id is not null and notice_id is null))
);

create index notifications_user_created_idx on public.notifications(user_id, created_at desc);
create index calendar_events_user_date_idx on public.calendar_events(user_id, event_date);

create or replace function public.current_profile_id()
returns bigint language sql stable security definer set search_path = public
as $$ select id from public.users where auth_user_id = auth.uid() and active limit 1 $$;

create or replace function public.current_profile_role()
returns text language sql stable security definer set search_path = public
as $$ select role from public.users where auth_user_id = auth.uid() and active limit 1 $$;

create or replace function public.get_student_email(p_roll_no text)
returns text language sql stable security definer set search_path = public
as $$
  select u.email
  from public.users u join public.students s on s.user_id = u.id
  where u.active and lower(s.roll_no) = lower(trim(p_roll_no))
  limit 1
$$;
revoke all on function public.get_student_email(text) from public, anon, authenticated;

create or replace function public.is_profile_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select coalesce(public.current_profile_role() = 'admin', false) $$;

create or replace function public.is_hod()
returns boolean language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.faculty f
    where f.user_id = public.current_profile_id() and f.is_hod
  )
$$;

create or replace function public.matches_current_audience(target_department text, target_year text, target_section text)
returns boolean language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.students s
    join public.users u on u.id = s.user_id
    where u.auth_user_id = auth.uid() and u.active
      and (target_department is null or target_department = '' or target_department = s.department or target_department = s.program_code)
      and (target_year is null or target_year = '' or target_year = s.year)
      and (target_section is null or target_section = '' or target_section = s.section)
  )
$$;

create or replace function public.can_access_material_file(object_name text)
returns boolean language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.materials m
    join public.users uploader on uploader.id = m.uploaded_by
    where m.storage_path = object_name
      and (
        public.is_profile_admin()
        or m.uploaded_by = public.current_profile_id()
        or (
          m.visibility = 'published'
          and exists (
            select 1 from public.students s
            join public.users student_user on student_user.id = s.user_id
            where student_user.auth_user_id = auth.uid() and student_user.active
              and s.program_code = m.program_code
              and s.year = (select c.year from public.courses c where c.id = m.course_id)
              and (nullif((select c.section from public.courses c where c.id = m.course_id), '') is null
                or s.section = (select c.section from public.courses c where c.id = m.course_id))
          )
        )
      )
  )
$$;

create or replace function public.can_access_notice_image(object_name text)
returns boolean language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.notices n
    where n.image_path = object_name
      and (
        public.is_profile_admin()
        or n.created_by = public.current_profile_id()
        or (
          n.status = 'published' and n.publish_at <= now()
          and (
            (n.course_id is null and public.matches_current_audience(n.department, n.year, n.section))
            or exists (
              select 1 from public.courses c
              join public.students s on s.program_code = c.program_code and s.year = c.year
                and (nullif(c.section, '') is null or s.section = c.section)
              where c.id = n.course_id and s.user_id = public.current_profile_id()
            )
          )
        )
      )
  )
$$;

create or replace function public.get_course_student_emails(p_course_id bigint, p_year text)
returns table (name text, email text, roll_no text, program_code text, year text, section text)
language plpgsql stable security definer set search_path = public
as $$
declare
  target_course public.courses%rowtype;
begin
  if not public.is_hod() and not public.is_profile_admin() then
    raise exception 'HOD or administrator access is required';
  end if;
  select * into target_course from public.courses where id = p_course_id;
  if not found then raise exception 'Course not found'; end if;
  if p_year is null or p_year = '' then raise exception 'Year is required'; end if;
  return query
    select u.name, u.email, s.roll_no, s.program_code, s.year, s.section
    from public.students s
    join public.users u on u.id = s.user_id
    where u.active and s.program_code = target_course.program_code and s.year = p_year
      and (nullif(target_course.section, '') is null or s.section = target_course.section)
    order by s.section, u.name;
end;
$$;

create or replace function public.register_student_from_auth()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
  student_name text := trim(coalesce(new.raw_user_meta_data->>'name', ''));
  student_roll text := trim(coalesce(new.raw_user_meta_data->>'roll_no', ''));
  student_program text := lower(trim(coalesce(new.raw_user_meta_data->>'program_code', '')));
  student_department text := trim(coalesce(new.raw_user_meta_data->>'department', ''));
  student_year text := trim(coalesce(new.raw_user_meta_data->>'year', ''));
  student_section text := trim(coalesce(new.raw_user_meta_data->>'section', ''));
begin
  if new.raw_user_meta_data->>'registration_role' is distinct from 'student' then
    return new;
  end if;
  if new.email is null or lower(new.email) !~ '^[^@[:space:]]+@gmail\.com$'
    or student_name = '' or student_roll = '' or student_program !~ '^[a-z]{2,8}$'
    or student_department = '' or student_year = '' or student_section = '' then
    raise exception 'Enter your name, roll number, department, program, Gmail address, year, section, and password.';
  end if;
  insert into public.users (auth_user_id, name, email, role, roll_no, department, year, section, active)
  values (new.id, student_name, lower(new.email), 'student', student_roll,
    student_department, student_year, student_section, true);
  insert into public.students (user_id, roll_no, program_code, department, year, section)
  select id, student_roll, student_program, student_department, student_year, student_section
  from public.users where auth_user_id = new.id;
  return new;
end;
$$;

drop trigger if exists on_auth_user_registered on auth.users;
create trigger on_auth_user_registered after insert on auth.users
for each row execute function public.register_student_from_auth();

create or replace function public.notify_notice_audience()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if new.status <> 'published' then return new; end if;
  if tg_op = 'UPDATE' and old.status = 'published' then return new; end if;
  insert into public.notifications (user_id, event_type, title, body, notice_id)
  select s.user_id, 'notice', 'New notice: ' || new.title, left(new.body, 240), new.id
  from public.students s
  join public.users u on u.id = s.user_id and u.active
  where (
    (new.course_id is not null and exists (
      select 1 from public.courses c where c.id = new.course_id
        and c.program_code = s.program_code and c.year = s.year
        and (nullif(c.section, '') is null or c.section = s.section)
    ))
    or
    (new.course_id is null
      and (new.department is null or new.department = '' or new.department = s.department or new.department = s.program_code)
      and (new.year is null or new.year = '' or new.year = s.year)
      and (new.section is null or new.section = '' or new.section = s.section))
  );
  return new;
end;
$$;
drop trigger if exists notice_notification_insert on public.notices;
create trigger notice_notification_insert after insert or update of status on public.notices
for each row execute function public.notify_notice_audience();

create or replace function public.notify_material_audience()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if new.visibility <> 'published' then return new; end if;
  if tg_op = 'UPDATE' and old.visibility = 'published' and old.version = new.version then return new; end if;
  insert into public.notifications (user_id, event_type, title, body, material_id)
  select s.user_id, 'material', 'New material: ' || new.title, new.unit || ' has new course material.', new.id
  from public.students s
  join public.users u on u.id = s.user_id and u.active
  join public.courses c on c.id = new.course_id and c.program_code = s.program_code and c.year = s.year
    and (nullif(c.section, '') is null or c.section = s.section);
  return new;
end;
$$;
drop trigger if exists material_notification_insert on public.materials;
create trigger material_notification_insert after insert or update of visibility, version on public.materials
for each row execute function public.notify_material_audience();

create or replace view public.account_directory with (security_invoker = false) as
  select u.id, u.name, u.role, u.active,
    s.roll_no, s.program_code, s.department, s.year, s.section,
    f.is_hod, f.department as faculty_department
  from public.users u
  left join public.students s on s.user_id = u.id
  left join public.faculty f on f.user_id = u.id
  where public.is_profile_admin()
    or (
      public.current_profile_role() = 'faculty'
      and (
        u.role = 'faculty'
        or (
          u.role = 'student'
          and (
            public.is_hod()
            or exists (
              select 1 from public.courses c
              where c.faculty_id = public.current_profile_id()
                and c.program_code = s.program_code and c.year = s.year
                and (nullif(c.section, '') is null or c.section = s.section)
            )
          )
        )
      )
    );
grant select on public.account_directory to authenticated;

do $$
declare
  existing_policy record;
begin
  for existing_policy in
    select tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename in (
        'users', 'students', 'faculty', 'administrators', 'legacy_student_records',
        'courses', 'notices', 'read_receipts', 'materials', 'material_views', 'bookmarks'
      )
  loop
    execute format('drop policy if exists %I on public.%I', existing_policy.policyname, existing_policy.tablename);
  end loop;
end $$;

drop policy if exists "courses visible to authenticated users" on public.courses;
drop policy if exists "admins manage courses" on public.courses;
drop policy if exists "notices visible by role and audience" on public.notices;
drop policy if exists "staff create notices" on public.notices;
drop policy if exists "owners and admins update notices" on public.notices;
drop policy if exists "owners and admins delete notices" on public.notices;
drop policy if exists "materials visible to owner staff and enrolled class" on public.materials;
drop policy if exists "staff upload materials" on public.materials;
drop policy if exists "owners and admins update materials" on public.materials;
drop policy if exists "owners and admins delete materials" on public.materials;

alter table public.users enable row level security;
alter table public.students enable row level security;
alter table public.faculty enable row level security;
alter table public.administrators enable row level security;
alter table public.courses enable row level security;
alter table public.notices enable row level security;
alter table public.read_receipts enable row level security;
alter table public.materials enable row level security;
alter table public.material_views enable row level security;
alter table public.bookmarks enable row level security;
alter table public.calendar_events enable row level security;
alter table public.notifications enable row level security;
alter table public.legacy_student_records enable row level security;

create policy "users visible to self and admins" on public.users
  for select to authenticated using (auth_user_id = auth.uid() or public.is_profile_admin());
create policy "admins update users" on public.users
  for update to authenticated using (public.is_profile_admin()) with check (public.is_profile_admin());
create policy "students visible to self and admins" on public.students
  for select to authenticated using (user_id = public.current_profile_id() or public.is_profile_admin());
create policy "faculty visible to self and admins" on public.faculty
  for select to authenticated using (user_id = public.current_profile_id() or public.is_profile_admin());
create policy "administrators visible to self and admins" on public.administrators
  for select to authenticated using (user_id = public.current_profile_id() or public.is_profile_admin());

create policy "courses visible to assigned audience" on public.courses
  for select to authenticated using (
    public.is_profile_admin()
    or public.is_hod()
    or faculty_id = public.current_profile_id()
    or exists (
      select 1 from public.students s
      where s.user_id = public.current_profile_id() and s.program_code = courses.program_code
        and s.year = courses.year and (nullif(courses.section, '') is null or s.section = courses.section)
    )
  );
create policy "admins manage courses" on public.courses
  for all to authenticated using (public.is_profile_admin()) with check (public.is_profile_admin());

create policy "notices visible to owner admin or targeted students" on public.notices
  for select to authenticated using (
    public.is_profile_admin() or created_by = public.current_profile_id()
    or (
      status = 'published' and publish_at <= now()
      and (
        (course_id is not null and exists (
          select 1 from public.courses c join public.students s on s.user_id = public.current_profile_id()
          where c.id = course_id and c.program_code = s.program_code and c.year = s.year
            and (nullif(c.section, '') is null or c.section = s.section)
        ))
        or (course_id is null and public.matches_current_audience(department, year, section))
      )
    )
  );
create policy "faculty and admins create notices" on public.notices
  for insert to authenticated with check (
    created_by = public.current_profile_id()
    and (public.is_profile_admin()
      or (public.current_profile_role() = 'faculty'
        and (public.is_hod() or (course_id is not null and exists (
          select 1 from public.courses c where c.id = course_id and c.faculty_id = public.current_profile_id()
        )))))
  );
create policy "notice owners and admins update" on public.notices
  for update to authenticated using (created_by = public.current_profile_id() or public.is_profile_admin())
  with check (created_by = public.current_profile_id() or public.is_profile_admin());
create policy "notice owners and admins delete" on public.notices
  for delete to authenticated using (created_by = public.current_profile_id() or public.is_profile_admin());

create policy "read receipts visible to reader and notice staff" on public.read_receipts
  for select to authenticated using (
    user_id = public.current_profile_id()
    or public.is_profile_admin()
    or exists (
      select 1 from public.notices n
      where n.id = notice_id and n.created_by = public.current_profile_id()
    )
  );
create policy "students create own read receipts" on public.read_receipts
  for insert to authenticated with check (
    user_id = public.current_profile_id() and public.current_profile_role() = 'student'
  );
create policy "students update own read receipts" on public.read_receipts
  for update to authenticated using (
    user_id = public.current_profile_id() and public.current_profile_role() = 'student'
  ) with check (
    user_id = public.current_profile_id() and public.current_profile_role() = 'student'
  );

create policy "materials visible to uploader admin or enrolled students" on public.materials
  for select to authenticated using (
    public.is_profile_admin() or public.is_hod() or uploaded_by = public.current_profile_id()
    or (
      visibility = 'published' and exists (
        select 1 from public.courses c join public.students s on s.user_id = public.current_profile_id()
        where c.id = course_id and c.program_code = s.program_code and c.year = s.year
          and (nullif(c.section, '') is null or c.section = s.section)
      )
    )
  );
create policy "faculty and admins upload materials" on public.materials
  for insert to authenticated with check (
    uploaded_by = public.current_profile_id()
    and (public.is_profile_admin() or (public.current_profile_role() = 'faculty' and (
      public.is_hod() or exists (
      select 1 from public.courses c where c.id = course_id and c.faculty_id = public.current_profile_id()
    ))))
  );
create policy "material owners and admins update" on public.materials
  for update to authenticated using (uploaded_by = public.current_profile_id() or public.is_profile_admin())
  with check (uploaded_by = public.current_profile_id() or public.is_profile_admin());
create policy "material owners and admins delete" on public.materials
  for delete to authenticated using (uploaded_by = public.current_profile_id() or public.is_profile_admin());

create policy "material views visible to reader and owner staff" on public.material_views
  for select to authenticated using (
    user_id = public.current_profile_id()
    or public.is_profile_admin()
    or exists (
      select 1 from public.materials m
      where m.id = material_id and m.uploaded_by = public.current_profile_id()
    )
  );
create policy "students record own material views" on public.material_views
  for insert to authenticated with check (
    user_id = public.current_profile_id() and public.current_profile_role() = 'student'
  );
create policy "users manage their own bookmarks" on public.bookmarks
  for all to authenticated using (user_id = public.current_profile_id())
  with check (user_id = public.current_profile_id());

create policy "users manage their own calendar events" on public.calendar_events
  for all to authenticated using (user_id = public.current_profile_id())
  with check (user_id = public.current_profile_id() and public.current_profile_role() = 'student');
create policy "users read their own notifications" on public.notifications
  for select to authenticated using (user_id = public.current_profile_id());
create policy "users mark their notifications read" on public.notifications
  for update to authenticated using (user_id = public.current_profile_id())
  with check (user_id = public.current_profile_id());

drop policy if exists "staff upload their own material files" on storage.objects;
drop policy if exists "authorized users read material files" on storage.objects;
drop policy if exists "owners and admins delete material files" on storage.objects;

create policy "faculty upload course materials" on storage.objects
  for insert to authenticated with check (
    bucket_id = 'materials'
    and (storage.foldername(name))[1] = public.current_profile_id()::text
    and (public.is_profile_admin() or public.current_profile_role() = 'faculty')
  );
create policy "users download authorized material files" on storage.objects
  for select to authenticated using (bucket_id = 'materials' and public.can_access_material_file(name));
create policy "owners and admins delete material files" on storage.objects
  for delete to authenticated using (
    bucket_id = 'materials'
    and ((storage.foldername(name))[1] = public.current_profile_id()::text or public.is_profile_admin())
  );

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('notice-images', 'notice-images', false, 10485760, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
create policy "faculty upload notice images" on storage.objects
  for insert to authenticated with check (
    bucket_id = 'notice-images'
    and (storage.foldername(name))[1] = public.current_profile_id()::text
    and (public.is_profile_admin() or public.current_profile_role() = 'faculty')
  );
create policy "students read targeted notice images" on storage.objects
  for select to authenticated using (bucket_id = 'notice-images' and public.can_access_notice_image(name));
create policy "notice image owners and admins delete" on storage.objects
  for delete to authenticated using (
    bucket_id = 'notice-images'
    and ((storage.foldername(name))[1] = public.current_profile_id()::text or public.is_profile_admin())
  );

grant execute on function public.is_hod() to authenticated;
grant execute on function public.matches_current_audience(text, text, text) to authenticated;
grant execute on function public.can_access_material_file(text) to authenticated;
grant execute on function public.can_access_notice_image(text) to authenticated;
grant execute on function public.get_course_student_emails(bigint, text) to authenticated;
grant execute on function public.register_student_from_auth() to service_role;

do $$
begin
  alter publication supabase_realtime add table public.notifications;
exception when duplicate_object then null;
end $$;
